from fastapi import APIRouter, HTTPException
from app.services.gemini_service import gemini_service
import random
import time

router = APIRouter(prefix="/whatsapp", tags=["whatsapp"])

# Sample phone numbers for mock data
PHONE_NUMBERS = [
    "573174799575@c.us",
    "573105767451@c.us",
    "573001234567@c.us",
    "573009876543@c.us",
    "573112233445@c.us"
]

@router.get("/messages")
async def get_messages(count: int = 5):
    """
    Get mock WhatsApp messages with random content generated by Gemini.
    """
    try:
        # Generate random message texts using Gemini
        message_texts = await gemini_service.generate_whatsapp_messages(count)
        
        messages = []
        for text in message_texts:
            # Pick random from/to numbers
            from_number = random.choice(PHONE_NUMBERS)
            to_number = random.choice([n for n in PHONE_NUMBERS if n != from_number])
            
            messages.append({
                "text": text,
                "source": "whatsapp",
                "from": from_number,
                "to": to_number
            })
        
        return messages
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
